plugin_dir: ~/.config/pydeck/plugins
icons_dir: ~/.config/pydeck/icons

pages:
  - name: main
    brightness: 80
    buttons:
      0:
        icon: play-pause.png
        action:
          type: command
          value: "playerctl play-pause"
      1:
        icon: mic-mute.png
        action:
          type: command
          value: "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
      5:
        icon: custom.png
        action:
          type: plugin
          value: "example_plugin:on_press"
