plugin_dir: ~/.config/pydeck/plugins
icons_dir: ~/.config/pydeck/icons

pages:
  - name: main
    brightness: 80
    buttons:
      0:
        icon: play-pause.png
        action:
          type: command
          value: "playerctl play-pause"

      1:
        states:
          - name: unmuted
            icon: mic-on.png
            action:
              type: command
              value: "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 1"
          - name: muted
            icon: mic-mute.png
            action:
              type: command
              value: "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 0"

      2:
        icon: chromium.png
        action:
          type: command
          value: "hyprctl dispatch focuswindow class:chromium || chromium &"

      3:
        icon: lemmings-walk.gif
        pressed_icon: lemmings-explode.gif
        action:
          type: command
          value: "killall firefox Discord"

      4:
        icon: firefox.png
        action:
          type: command
          value: "hyprctl dispatch focuswindow class:firefox || firefox &"

      5:
        icon: steam.png
        action:
          type: command
          value: "hyprctl dispatch focuswindow class:steam || steam &"
